-- =============================================================================
-- SCRIPT DDL: SISTEMA_VENDAS_DDL_V1.0
-- MODELO FÍSICO DO SISTEMA DE VENDAS E ANÁLISE COMERCIAL (ORACLE APEX)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 0. LIMPEZA PREVENTIVA (DESCOMENTE CASO PRECISE RECRIAR O ESQUEMA DO ZERO)
-- -----------------------------------------------------------------------------
/*
DROP TABLE tb_venda_item CASCADE CONSTRAINTS;
DROP TABLE tb_venda CASCADE CONSTRAINTS;
DROP TABLE tb_produto CASCADE CONSTRAINTS;
DROP TABLE tb_categoria CASCADE CONSTRAINTS;
DROP TABLE tb_vendedor CASCADE CONSTRAINTS;
DROP TABLE tb_cliente CASCADE CONSTRAINTS;
*/

-- -----------------------------------------------------------------------------
-- 1. TB_CATEGORIA
-- Entidade base sem dependências externas.
-- -----------------------------------------------------------------------------
CREATE TABLE tb_categoria (
    id_categoria NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome         VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_tb_categoria PRIMARY KEY (id_categoria)
);

-- -----------------------------------------------------------------------------
-- 2. TB_CLIENTE
-- Entidade independente contendo unicidade de CPF e E-mail.
-- -----------------------------------------------------------------------------
CREATE TABLE tb_cliente (
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome       VARCHAR2(150) NOT NULL,
    email      VARCHAR2(100) NOT NULL,
    cpf        VARCHAR2(11),
    ativo      CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT pk_tb_cliente PRIMARY KEY (id_cliente),
    CONSTRAINT uq_tb_cliente_email UNIQUE (email),
    CONSTRAINT uq_tb_cliente_cpf UNIQUE (cpf),
    CONSTRAINT ck_tb_cliente_ativo CHECK (ativo IN ('S', 'N'))
);

-- -----------------------------------------------------------------------------
-- 3. TB_VENDEDOR
-- Cadastro da equipe comercial.
-- -----------------------------------------------------------------------------
CREATE TABLE tb_vendedor (
    id_vendedor NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome        VARCHAR2(150) NOT NULL,
    email       VARCHAR2(100) NOT NULL,
    ativo       CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT pk_tb_vendedor PRIMARY KEY (id_vendedor),
    CONSTRAINT uq_tb_vendedor_email UNIQUE (email),
    CONSTRAINT ck_tb_vendedor_ativo CHECK (ativo IN ('S', 'N'))
);

-- -----------------------------------------------------------------------------
-- 4. TB_PRODUTO
-- Depende de TB_CATEGORIA.
-- -----------------------------------------------------------------------------
CREATE TABLE tb_produto (
    id_produto   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_categoria NUMBER NOT NULL,
    sku          VARCHAR2(50) NOT NULL,
    nome         VARCHAR2(150) NOT NULL,
    preco_unit   NUMBER(10, 2) NOT NULL,
    CONSTRAINT pk_tb_produto PRIMARY KEY (id_produto),
    CONSTRAINT uq_tb_produto_sku UNIQUE (sku),
    CONSTRAINT fk_tb_produto_categoria FOREIGN KEY (id_categoria) 
        REFERENCES tb_categoria (id_categoria),
    CONSTRAINT ck_tb_produto_preco CHECK (preco_unit > 0)
);

-- -----------------------------------------------------------------------------
-- 5. TB_VENDA
-- Depende de TB_CLIENTE e TB_VENDEDOR.
-- -----------------------------------------------------------------------------
CREATE TABLE tb_venda (
    id_venda      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cliente    NUMBER NOT NULL,
    id_vendedor   NUMBER NOT NULL,
    dt_venda      DATE DEFAULT SYSDATE NOT NULL,
    valor_liquido NUMBER(12, 2),
    canal         VARCHAR2(20) NOT NULL,
    status        VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_tb_venda PRIMARY KEY (id_venda),
    CONSTRAINT fk_tb_venda_cliente FOREIGN KEY (id_cliente) 
        REFERENCES tb_cliente (id_cliente),
    CONSTRAINT fk_tb_venda_vendedor FOREIGN KEY (id_vendedor) 
        REFERENCES tb_vendedor (id_vendedor),
    CONSTRAINT ck_tb_venda_canal CHECK (canal IN ('APP', 'SITE', 'LOJA', 'TELEFONE')),
    CONSTRAINT ck_tb_venda_status CHECK (status IN ('ABERTA', 'FECHADA', 'CANCELADA'))
);

-- -----------------------------------------------------------------------------
-- 6. TB_VENDA_ITEM
-- Depende de TB_VENDA e TB_PRODUTO. Implementa exclusão em cascata.
-- -----------------------------------------------------------------------------
CREATE TABLE tb_venda_item (
    id_venda_item       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_venda            NUMBER NOT NULL,
    id_produto          NUMBER NOT NULL,
    quantidade          NUMBER NOT NULL,
    valor_unit          NUMBER(10, 2) NOT NULL,
    percentual_desconto NUMBER(5, 2) DEFAULT 0 NOT NULL,
    valor_total         NUMBER(12, 2),
    CONSTRAINT pk_tb_venda_item PRIMARY KEY (id_venda_item),
    CONSTRAINT fk_tb_venda_item_venda FOREIGN KEY (id_venda) 
        REFERENCES tb_venda (id_venda) ON DELETE CASCADE,
    CONSTRAINT fk_tb_venda_item_produto FOREIGN KEY (id_produto) 
        REFERENCES tb_produto (id_produto),
    CONSTRAINT ck_tb_item_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_tb_item_desconto CHECK (percentual_desconto BETWEEN 0 AND 50)
);
